fix: sort-order rule don't change sub-keys
JoshuaKGoldberg/eslint-plugin-package-json pull request #312
Opened 2024-04-13 15:09 UTC by hyoban

## PR Checklist

-   [x] Addresses an existing open issue: fixes #80 
-   [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

2024-04-27 14:03 UTC, hyoban commented
@JoshuaKGoldberg Sorry for the direct ping, I don't want you to miss this one. Please feel free to review it when you have time.

2024-04-28 19:25 UTC, JoshuaKGoldberg requested changes
This looks great, thanks! Just the one testing request. 🚀 

Also - I think this is a big enough change (new dependencies, better auto-fix) that even though it's technically a bugfix, I'd like it to give it as a minor release rather than a patch. Renaming to `feat: ...`.

2024-04-28 19:25 UTC, JoshuaKGoldberg commented on src/tests/rules/order-properties.test.ts
[Testing] Could you add a `valid` case where the top-level keys are sorted but sub-keys aren't? That way we know the logic is still just looking at the top-level keys.

2024-04-28 19:25 UTC, JoshuaKGoldberg commented on src/rules/order-properties.ts
> +									result,
[Praise] Nice, this results in better-preserved formatting for all auto-fixes!

2024-04-28 19:26 UTC, JoshuaKGoldberg commented
Thanks for the ping! I've been in and out of being swamped with ESLint v9 / typescript-eslint v8 work, just emerging from that cocoon now. 😄

2024-04-29 12:21 UTC, JoshuaKGoldberg approved these changes
![A bunch of triumphant Mets players cheering while one guy in particular is whooping and walking](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/assets/3335181/39cd0bcc-72af-4b72-84f2-1b6241b3883c)

2024-04-29 12:25 UTC, merged